apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
data:
  api-key: MmFkY2RiZTlmMTUzNWY1YzU1MTc2OWVmZDg0NWQ4NGYK
  app-key: Y2IyMjJlMDhiNmRhMzJhMGNiNjZlNGY3NmQ3ZTcyYzQwNzFjYzE0MQo=
