apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-read-deployment
  labels:
    app: nest-read
    tags.datadoghq.com/env: home
    tags.datadoghq.com/service: nest
    tags.datadoghq.com/version: "2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-read
  template:
    metadata:
      labels:
        app: nest-read
        tags.datadoghq.com/env: home
        tags.datadoghq.com/service: nest
        tags.datadoghq.com/version: "2.0"
#        admission.datadoghq.com/enabled: "true"
#      annotations:
#        admission.datadoghq.com/python-lib.version: v1.15.0
    spec:
      containers:
      - name: nest-read
        image: ethomatos/nest:latest
        imagePullPolicy: Always
        env:
        - name: DD_ENV
          value: "home"
        - name: DD_SERVICE
          value: "nest"
        - name: DD_VERSION
          value: "4.0"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: app-key
        - name: CLIENTID
          valueFrom:
            secretKeyRef:
              name: nest-initvars-secret
              key: clientID
        - name: CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: nest-initvars-secret
              key: clientSecret
        - name: PROJECTID
          valueFrom:
            secretKeyRef:
              name: nest-initvars-secret
              key: projectID
        - name: REFRESHTOKEN
          valueFrom:
            secretKeyRef:
              name: nest-initvars-secret
              key: refreshToken
