apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-app
  labels:
    app: bar-app
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: bar-app
  replicas: 2
  template:
    metadata:
      labels:
        app: bar-app
    spec:
      containers:
      - name: bar-app
        image: ethomatos/k8s-app
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: BAR
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-app
  labels:
    app: foo-app
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: foo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
      - name: foo-app
        image: ethomatos/k8s-app
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: FOO
---  
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /foo
          backend:
            serviceName: foo-app
            servicePort: 8080
        - path: /bar
          backend:
            serviceName: bar-app
            servicePort: 8080
