apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-getip-deployment
  labels:
    app: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: ethomatos/speedtest:latest
